### ISSUE TITLE
List: Ext2 and BilbyFS verified compilation

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#199]
<a href="https://github.csiro.au/lim060"><img src="https://github.csiro.au/avatars/u/271?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lim060](https://github.csiro.au/lim060)**
_Fri Aug  7 17:50:53 2015_
_Originally opened as https://github.csiro.au/ts-filesystems/Cogent/issues/94_

----

Current status:
- [x] Normalisation: done in 403397c95 by reimplementing A-normalisation in Isabelle. Related issue: #92.
- [x] Shallow-deep refinement: done in 4dc25e5ce, should be stable.
- [ ] C refinement. Known issues:
  - [x] Allow `AFun`s as parameters. Should only need to tweak the `HO_call_hints` and `corres_tac_driver` code. Ext2 used this a few times and we could fix them by hand (wrap them in `Fun`s). BilbyFS uses a lot of them:
    
    `grep -Po '(?<!App \()AFun [^ ]+ \[[^]]*\]' BilbyFS_TypeProof.thy | sort -u`
  - [x] Some BilbyFS code creates unused C variables, which used to throw spanners into the baroque C-refinement mechanism. See issue #95.
  - [ ] Extremely long round-trip time (tens of hours). We can easily improve the corres prover (issue #98), but C-parser and AutoCorres are also big time sinks. Issue #98.
  - [ ] Second-order unification. The unifier uses a finite search depth, and instantiations for Case rules can be arbitrarily large (grows with program size). Could be solved by rolling our own matcher, if more diplomatic approaches fail. Or by modifying codegen for Case.
- [x] Monomorphisation. Not an issue for Ext2, but BilbyFS uses polymorphic `Rbt` and `wordarray` (non-abstract) functions:
  
  `grep -Po 'App \(Fun [^ ]+ \[[^]]+\]\)' BilbyFS_Deep_Normal.thy | sort -u`
  
  The compiler should generate the mapping for us (analogous to `printAFM`). Then we have to keep track of the instantiations in `Mono_Tac`.
  - Status: done. Instead of modifying the compiler, we get the mapping in ML in a horrible way by inverting the existing poly-to-mono mapping.
- [x] End-to-end refinement. The compiler should generate a refinement theorem for each function (or perhaps just each top-level function).
  - Status: done (for top-level functions, but see #99).
