### ISSUE TITLE
[CLOSED] Packaging checklist

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#209]
<a href="https://github.csiro.au/lim060"><img src="https://github.csiro.au/avatars/u/271?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lim060](https://github.csiro.au/lim060)**
_Tue Nov 17 20:18:47 2015_
_Originally opened as https://github.csiro.au/ts-filesystems/Cogent/issues/104_

----

Checklist for PLDI submission packaging (20 November).

Packaging script and file list: [release/release.sh](https://github.inside.nicta.com.au/ts-filesystems/bilby/tree/master/release/release.sh)
Licenses: [license-cleanup](https://github.inside.nicta.com.au/ts-filesystems/bilby/tree/license-cleanup)
- [x] Peer review for packaging script/file list
- [ ] Review and merge license-cleanup
- [x] Check regression tests (11/11 tests passed).
- [x] Check regression tests in VM
- [x] Check file system proofs (lemma)
  - [x] BilbyFS (20151117 snapshot + backports)
  - [x] ext2 (20151117 snapshot + backports)
- [ ] Check file system proofs in VM?
- [x] [Hot-patches for file system proofs](https://github.inside.nicta.com.au/ts-filesystems/bilby/tree/master/release/BilbyFS_CorresProof.patch)
- [X] [Release-specific README](https://github.inside.nicta.com.au/ts-filesystems/bilby/tree/master/release/README.release)
- [ ] Release-specific top-level build script?

**Comment by zilinc** [comment]
<a href="https://github.csiro.au/lim060"><img src="https://github.csiro.au/avatars/u/271?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lim060](https://github.csiro.au/lim060)**
_Tue Nov 17 22:15:29 2015_

----

Make release:

```
release/release.sh --license-tool="license-tool/expand_license.py release/license_expand"
```

BilbyFS compilation:

```
cd release-*/impl/bilby/dsl
make verification
patch <../../../../release/BilbyFS_CorresProof.patch
../../../isabelle/bin/isabelle build -d . -d ../../../cdsl/isa -d ../../../l4v -v -b -o process_output_limit=999 BilbyFS_AllRefine
```

ext2 compilation:

```
release-*/impl/ext2/build.sh verification clean
```

**Comment by zilinc** [comment]
<a href="https://github.csiro.au/che283"><img src="https://github.csiro.au/avatars/u/286?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [che283](https://github.csiro.au/che283)**
_Wed Nov 18 11:07:31 2015_

----

@jalim where's this figure (11/15 tests passed) from?

**Comment by zilinc** [comment]
<a href="https://github.csiro.au/lim060"><img src="https://github.csiro.au/avatars/u/271?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lim060](https://github.csiro.au/lim060)**
_Wed Nov 18 16:28:18 2015_

----

@zchen
From running the release script [above](https://github.inside.nicta.com.au/ts-filesystems/bilby/issues/104#issuecomment-9718)

**Comment by zilinc** [comment]
<a href="https://github.csiro.au/che283"><img src="https://github.csiro.au/avatars/u/286?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [che283](https://github.csiro.au/che283)**
_Wed Nov 18 16:50:57 2015_

----

done with my review.

**Comment by zilinc** [comment]
<a href="https://github.csiro.au/lim060"><img src="https://github.csiro.au/avatars/u/271?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lim060](https://github.csiro.au/lim060)**
_Mon Nov 30 14:47:49 2015_

----

Was released: http://ssrg.nicta.com.au/Private/downloads/TScompiler/
